// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBar2V6S6lSHV_yzeIGW9R2CuSsTCr6mkM',
    appId: '1:345978721804:web:701194606221a19dee4029',
    messagingSenderId: '345978721804',
    projectId: 'fruits-dc1d4',
    authDomain: 'fruits-dc1d4.firebaseapp.com',
    storageBucket: 'fruits-dc1d4.firebasestorage.app',
    measurementId: 'G-H7RJ7J50DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7NQT7BLeH0uIzgx8ix5t4MkAn65XhV4',
    appId: '1:345978721804:android:fe69055de897e411ee4029',
    messagingSenderId: '345978721804',
    projectId: 'fruits-dc1d4',
    storageBucket: 'fruits-dc1d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0Nuf6-yi_58QqrGuSsEN0Z-PfJspe0w',
    appId: '1:345978721804:ios:82ee0079057c887bee4029',
    messagingSenderId: '345978721804',
    projectId: 'fruits-dc1d4',
    storageBucket: 'fruits-dc1d4.firebasestorage.app',
    androidClientId: '345978721804-v0aq36hn3s4dh3v435k566c0due71cj6.apps.googleusercontent.com',
    iosClientId: '345978721804-s91nm4hmbks9sp5oq4qejebmqkddvqaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBar2V6S6lSHV_yzeIGW9R2CuSsTCr6mkM',
    appId: '1:345978721804:web:d99736491da548b6ee4029',
    messagingSenderId: '345978721804',
    projectId: 'fruits-dc1d4',
    authDomain: 'fruits-dc1d4.firebaseapp.com',
    storageBucket: 'fruits-dc1d4.firebasestorage.app',
    measurementId: 'G-WTNW8S2VBQ',
  );
}
